language: node_js
node_js:
  - "7"
install:
  - npm install
  - npm --prefix ./tests install
  - npm --prefix ./tests/nightwatch install
cache:
  directories:
  - node_modules
  - test/node_modules
  - test/sandbox/nightwatch/node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm --prefix ./tests start  &

addons:
 chrome: stable
